name = "sig-laborer"
main = "src/index.ts"
compatibility_date = "2024-12-23"

[[kv_namespaces]]
binding = "FORM_DATA_KV"
id = "3ba2510178b74c248d0fe2283f5889c9"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mark-images"
